name: shivang_s_crud
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.6
  grouped_list: ^5.1.2
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
